// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xkkcmeaykkwnsojvgujt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhra2NtZWF5a2t3bnNvanZndWp0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ1Njg1OTMsImV4cCI6MjA3MDE0NDU5M30.f_MSMpFl2UgcGhMvNNyBl_4HchXdJIb1pZ1cemYLKIs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});